import luigi
import time


class Task1(luigi.Task):
    task_namespace = 'tasks'

    def run(self):
        print("Task1: run")
        with self.output().open("w") as target:
            # target.write(f"This file was generated by Task1 at {time.asctime()}.")
            target.write("this file was generated by Task1 at %s." % time.asctime())

    def output(self):
        print("Task1: output")
        return luigi.LocalTarget("intermediate/task1_%s.txt" % time.asctime())


class Task2(luigi.Task):
    task_namespace = 'tasks'

    def requires(self):
        print("Task2: requires")
        return Task1()

    def run(self):
        print("Task2: run")
        with self.input().open("r") as intermediate, self.output().open("w") as target:
            task1_text = intermediate.read()

            target.write(task1_text)
            target.write("This file was generated by Task2 at %s." % time.asctime())

    def output(self):
        print("Task2: output")
        return luigi.LocalTarget("output/task2_%s.txt" % time.asctime())


if __name__ == '__main__':
    # luigi.run(['tasks.Task2', '--workers', '1', '--local-scheduler'])
    luigi.run(['tasks.Task2', '--workers', '1'])

